### PR TITLE
HCLOUD-3007_Default-node-spec-to-version-1-in-engine_Jorge-Brown

### PR DESCRIPTION
**Pull request by JorgePBrown**

### CODE REVIEW

**Comment by ArturGrafov** [comment]
Task linked: [HCLOUD-3007 Default node spec to version 1 in engine](https://app.clickup.com/t/2570196/HCLOUD-3007)

**Review by DariusWe — COMMENTED** [review]
I don't understand the reason for this change, even after reading the ticket, probably because i don't know in which scenario specVersion can be undefined. I think a method called `isStreamNodeSpecificationV1` should not return true if specVersion is undefined, but if really necessary a short comment above the line explaining the reason would be appreciated.

**Comment by ArturGrafov** [comment]
> I don't quite understand the reason for this change, probably because i don't know in which scenario specVersion can be undefined. A short comment above the line explaining the reason would be appreciated.

I think it's for downwards compability reasons. SpecVersion property got introduced in a later state, so there might be old entities out there, which have this property not set.

**Comment by JorgePBrown** [comment]
> I don't quite understand the reason for this change, probably because i don't know in which scenario specVersion can be undefined. A short comment above the line explaining the reason would be appreciated.

It's because we have code like this in the engine which causes old nodes to not work. It may be a cause of our compatibility issues. It should only throw the exception when it is defined and a version that we actually don't know, since the undefined version is the initial one before the specVersion property got added.

```ts
const spec = this.node.getNodeSpecification();
if (isStreamNodeSpecificationV1(spec)) {
    return spec.inputs?.find(i => i.name === inputName);
} else {
    throw new UnknownStreamNodeSpecificationVersion(spec);
}
```

**Comment by DariusWe** [comment]
Okay, thanks for the answers. I would still appreciate a comment above the line explaining that in a short sentence, because it's not obvious from the code alone. Just merge it then!

**Pull request merged**
